export const FETCH_DELIVERIES_SUCCESS = "FETCH_DELIVERIES_SUCCESS";
export const FETCH_DELIVERIES_ERROR = "FETCH_DELIVERIES_ERROR";
export const CREATE_DELIVERY_SUCCESS = "CREATE_DELIVERY_SUCCESS";
export const CREATE_DELIVERY_ERROR = "CREATE_DELIVERY_ERROR";
export const UPDATE_DELIVERY_SUCCESS = "UPDATE_DELIVERY_SUCCESS";
export const UPDATE_DELIVERY_ERROR = "UPDATE_DELIVERY_ERROR";
export const DELETE_DELIVERY_SUCCESS = "DELETE_DELIVERY_SUCCESS";
export const DELETE_DELIVERY_ERROR = "DELETE_DELIVERY_ERROR";

export const SET_LOADING = "SET_LOADING";
export const SET_NEW_DELIVERY = "SET_NEW_DELIVERY";
export const SET_MODAL_TYPE = "SET_MODAL_TYPE";
export const SET_ERROR = "SET_ERROR";
export const SET_SELECTED_DELIVERY = "SET_SELECTED_DELIVERY";
export const TOGGLE_CREATE_EDIT_MODAL = "TOGGLE_CREATE_EDIT_MODAL";

