const apiUrl = {
  signIn: "/wapi/v1/account/auth:signin",
  signUp: "/wapi/v1/account/auth:signup",

  /* Araçlar */
  searchVehicles: "/wapi/v1/vehicles/search",
  createVehicle: "/wapi/v1/vehicles",
  updateVehicle: "/wapi/v1/vehicles",
  deleteVehicle: "/wapi/v1/vehicles",
  getVehicles: "/wapi/v1/vehicles/getVehicle",
  /* Araçlar */

  /* Paketler */
  searchPackages: "/wapi/v1/package/search",
  createPackage: "/wapi/v1/package",
  updatePackage: "/wapi/v1/package",
  deletePackage: "/wapi/v1/package",
  getPackages: "/wapi/v1/package/getPackage",
  /* Paketler */

  /*Ürünler*/
  searchProducts: "/wapi/v1/product/search",
  createProduct: "/wapi/v1/product",
  updateProduct: "/wapi/v1/product",
  deleteProduct: "/wapi/v1/product",
  getProducts: "/wapi/v1/product/getProduct",
  /*Ürünler*/

  /*Kullanıcılar*/
  searchUsers: "/wapi/v1/user/search",
  createUser: "/wapi/v1/user/createApi",
  updateUser: "/wapi/v1/user",
  deleteUser: "/wapi/v1/user",
  getUsers: "/wapi/v1/user/getUsers",
  /*Kullanıcılar*/

  /*Gönderiler*/
  searchDeliveries: "/wapi/v1/delivery/search",
  updateDelivery: "/wapi/v1/delivery/changeDeliveryStatus",
  createDelivery: "/wapi/v1/delivery",
  getDelivery:"/wapi/v1/delivery/getDelivery",
  deleteDelivery: "/wapi/v1/delivery",
  /*Gönderiler*/

  /*Depo*/
  searchWarehouses: "/wapi/v1/warehouse/search",
  updateWarehouse: "/wapi/v1/warehouse",
  createWarehouse: "/wapi/v1/warehouse",
  getWarehouse:"/wapi/v1/warehouse/getWarehouse",
  deleteWarehouse: "/wapi/v1/warehouse",
  /*Depo*/

  /*Seferler*/
  searchTransports: "/wapi/v1/transport/search",
  updateTransport: "/wapi/v1/transport",
  createTransport: "/wapi/v1/transport",
  getTransport:"/wapi/v1/transport/getTransport",
  deleteTransport: "/wapi/v1/transport",
  /*Seferler*/

  profilePhoto: "/wapi/v1/account/profile/photo",
  user: "/wapi/v1/account",
  passwordChange: "/wapi/v1/account/password",

  products: "/wapi/v1/product/search",
  orderProducts: "/wapi/v1/order/orderProducts",
  unitTypes: "/wapi/v1/product/unitTypes",
  product: "/wapi/v1/product",
  changeModelCodeAndCode: "/wapi/v1/product/changeModelCodeAndCode",
  productByBarcode: "/wapi/v1/product/getByBarcode",
  productSearchedAndExportExcel: "/wapi/v1/product/searchedAndExportExcel",
  productImport: "/wapi/v1/product/importProductExcel",
  updateProductExcel: "/wapi/v1/product/updateProductExcel",
  requestApproval: "/wapi/v1/product/requestApproval",
  categoryTree: "/wapi/v1/categoryFeature/tree",
  category: "/wapi/v1/categoryFeature",
  workers: "/wapi/v1/user/search",
  worker: "/wapi/v1/user",
  updateWorker: "/wapi/v1/user",
  addWorker: "/wapi/v1/account/auth:signup",
  warehouses: "/wapi/v1/warehouse/search",
  warehouse: "/wapi/v1/warehouse",
  countries: "/wapi/v1/country/search",
  getEUCountries: "/wapi/v1/country/getEUCountries",

  companies: "/wapi/v1/company/search",
  addCompany: "/wapi/v1/company",
  company: "/wapi/v1/company",
  companyList: "/wapi/v1/company/companyList",
  orders: "/wapi/v1/order/search",
  order: "/wapi/v1/order",
  orderAnalystApprove: "/wapi/v1/order/orderAnalystApprove",
  orderApproved: "/wapi/v1/order/orderApproved",
  importExcelToOrder: "/wapi/v1/order/importExcel",
  managerCancelled: "/wapi/v1/order/orderApprovedCancel",
  companyApproved: "/wapi/v1/order/orderCompanyApproved",
  companyCancelled: "/wapi/v1/order/orderCompanyCanceled",
  returns: "/wapi/v1/return/search",
  returnItem: "/wapi/v1/return",
  shelves: "/wapi/v1/rack/search",
  shelve: "/wapi/v1/rack",
  approvalCancel: "/wapi/v1/accept/approvalCancel",
  acceptDeliveryItem: "/wapi/v1/accept/item",
  getStockFromRack: "/wapi/v1/rack/getStockFromRack",
  deliveryCompanyConfirm: "/wapi/v1/accept/approvalCompany",
  deliveryCompanyCancel: "/wapi/v1/accept/approvalCompanyCancel",
  deliveryEnterWarehouse: "/wapi/v1/delivery/deliveryEnterWarehouse",
  deliveryAcceptByCompany: "/wapi/v1/delivery/deliveryAcceptedByCompany",
  getArrivedDeliveryByCode: "/wapi/v1/delivery/getArrivedDeliveryByCode",
  startPreparingDelivery: "/wapi/v1/delivery/startPreparingDelivery",
  deliveryAcceptedByGonderSatalim:
    "/wapi/v1/delivery/deliveryAcceptedByGonderSatalim",
  acceptProduct: "/wapi/v1/delivery/acceptProduct",
  preparedDelivery: "/wapi/v1/delivery/preparedDelivery",
  customDeliveryEnterWarehouse:
    "/wapi/v1/delivery/customDeliveryEnterWarehouse",
  shippedDelivery: "/wapi/v1/delivery/shippedDelivery",
  addInvoice: "/wapi/v1/delivery/addFileToDelivery",
  deleteInvoice: "/wapi/v1/delivery/deleteFileFromDelivery",
  acceptApproval: "/wapi/v1/accept/approval",
  api: "/wapi/v1/user/createApi",
  getApi: "/wapi/v1/user/getApi",
  getNextOrder: "/wapi/v1/order/getNextOrder",
  cancelPreparingOrder: "/wapi/v1/order/cancelPreparingOrder",
  cargoLabel: "/wapi/v1/order/cargoLabel",
  collectOrder: "/wapi/v1/order/collect",
  updateReturnBarcode: "/wapi/v1/order/updateReturnBarcode",
  box: "/wapi/v1/box",

  putProductToBox: "/wapi/v1/package/putProductToBox",
  completePackage: "/wapi/v1/package/completePackage",
  boxes: "/wapi/v1/box/search",
  boxByID: "/wapi/v1/box",
  createContract: "/wapi/v1/contract",
  getMenu: "/wapi/v1/menu/getMenu",
  fetchContracts: "/wapi/v1/contract/search",
  fetchContractById: "/wapi/v1/contract",
  addProductToContract: "/wapi/v1/contract/addProduct",
  updateContract: "/wapi/v1/contract",
  importExcelToContract: "/wapi/v1/contract/importExcel",
  addContract: "/wapi/v1/contract/addDocuments",
  deleteProductFromContract: "/wapi/v1/contract/deleteProduct",
  activateContract: "/wapi/v1/contract/activateContract",
  deactivateContract: "/wapi/v1/contract/deactivateContract",
  readyForDeliveryCancel: "/wapi/v1/order/readyForDeliveryCancelled",
  addImagesToProduct: "/wapi/v1/product/addImages",
  deleteImageFromProduct: "/wapi/v1/product/deleteImage",
  searchInvoices: "/wapi/v1/deliveryInvoice/search",
  exports: "/wapi/v1/exportation/search",
  export: "/wapi/v1/exportation",
  addPackagesToExport: "/wapi/v1/exportation/addPackages",
  fetchInvoiceById: "/wapi/v1/deliveryInvoice/",
  startExportPackage: "/wapi/v1/exportation/startExportPackage",
  exportPackage: "/wapi/v1/exportation/exportPackage",
  exportApprove: "/wapi/v1/exportation/exportationApprove",
  exportApproveCancel: "/wapi/v1/exportation/exportationApproveCancel",
  searchPayments: "/wapi/v1/payment/search",
  getPayment: "/wapi/v1/payment",
  cancelPayment: "/wapi/v1/payment/discardPayment",
  makePayment: "/wapi/v1/payment/makePayment",
  getImage: "/wapi/v1/imageApi/getImage",
  getMergedImage: "/wapi/v1/imageApi/getMergedImage",
  getMultipleBarcodes: "/wapi/v1/imageApi/getMultipleBarcodes",
  pdfToUrl: "/wapi/v1/imageApi/pdfToUrl",
  exportationSender: "/wapi/v1/exportation/exportationSender",
  exportationReceiver: "/wapi/v1/exportation/exportationReceiver",
  exportationReceiverWarehouse:
    "/wapi/v1/exportation/exportationReceiverWarehouse",
  exportationSearchedAndExportExcel:
    "/wapi/v1/exportation/searchedAndExportExcel",
  sendContactMail: "/wapi/v1/contact/sendContactMail",
  distributeProduct: "/wapi/v1/dataDistribution/distributeProduct",
};

export default apiUrl;
