export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_ERROR = "FETCH_COUNTRIES_ERROR";
export const GET_EU_COUNTRIES_SUCCESS = "GET_EU_COUNTRIES_SUCCESS";
export const GET_EU_COUNTRIES_ERROR = "GET_EU_COUNTRIES_ERROR";

export const SET_LOADING = "SET_LOADING";
export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY";